name: CI Test

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_DIR: ${{ github.workspace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:mhier/libboost-latest -y
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev libgtest-dev cmake valgrind
        cd /usr/src/gtest/
        sudo cmake CMakeLists.txt
        sudo make
      working-directory: /usr/src/gtest/

    - name: Prepare
      run: |
        cat /usr/include/boost/version.hpp | grep "BOOST_LIB_VERSION"
      working-directory: ${{ env.PROJECT_DIR }}

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake ..
      working-directory: ${{ env.PROJECT_DIR }}

    - name: Build
      run: |
        make
      working-directory: ${{ env.PROJECT_DIR/build }}

    - name: Run Tests
      run: |
        valgrind make test
        python3 ../tests/scenario_tests/tests.py
      working-directory: ${{ env.PROJECT_DIR/build }}